version: 2
updates:
  - package-ecosystem: 'github-actions'
    rebase-strategy: disabled
    directory: '/'
    schedule:
      interval: weekly

  - package-ecosystem: 'uv'
    directory: '/'
    rebase-strategy: disabled
    schedule:
      interval: weekly
    groups:
      # Group minor and patchs into a single PR
      regular-updates:
        update-types:
          - 'minor'
          - 'patch'
