[project]
name = "python-project-template"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = []

[dependency-groups]
dev = [
    "ruff>=0.13.0",
    "ty>=0.0.1a21",
]

[build-system]
requires = ["uv_build"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = "python_project_template"
module-root = "."

[tool.uv]
required-version = ">=0.8.4"

[tool.ruff]
target-version = 'py313'
line-length = 95
indent-width = 4

[tool.ruff.lint]
select = [
    "E",   # pycodestyle errors
    "W",   # pycodestyle warnings
    "F",   # pyflakes
    "N",   # pep8-naming
    "I",   # isort
    "RUF", # Ruff specific rules
]
ignore = [
    "E501", # line-too-long
    "T201", # print
]

[tool.ruff.lint.isort]
combine-as-imports = true

[tool.ty.environment]
root = ["python_project_template"]
python = "./.venv"
