name: All Tests

on: pull_request

jobs:
  lint:
    name: Lint and typecheck Python code
    runs-on:
      - runs-on=${{ github.run_id }}
      - job=lint
      - extras=s3-cache
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      - uses: citizensadvice/python-uv-setup-action@70884aff70491439526c3e437c25803b9e67aaed
      - uses: extractions/setup-just@53165ef7e734c5c07cb06b3c8e7b647c5aa16db3
      - run: just lint

  audit:
    name: Audit dependencies
    runs-on:
      - runs-on=${{ github.run_id }}
      - job=audit-dependencies
      - extras=s3-cache
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          sparse-checkout: |
            uv.lock
            justfile
            pyproject.toml
      - uses: astral-sh/setup-uv@11f9893b081a58869d3b5fccaea48c9e9e46f990
      - uses: extractions/setup-just@53165ef7e734c5c07cb06b3c8e7b647c5aa16db3
      - run: just audit
